### ISSUE TITLE
IP address error

### ISSUE THREAD

**Issue by albertorighetto** [phuvf/oscpoint#11]
Whenever I try to change the IP address to something different than 127.0.0.1 the following error occurs:

<img width="276" alt="IP address error" src="https://github.com/phuvf/oscpoint/assets/12547822/c28de9c5-ede9-4f7c-a6b1-378952223b21">

On 127.0.0.1 OSC is sent without problems.

Currently running on v1.0.1.1

**Comment by phuvf** [comment]
Thanks for the note - I can reproduce this error myself. I'll looking into this this evening.

**Comment by phuvf** [comment]
Think this was just a simple regex mix up on my part. This should now work on v1.0.1.2.

Let me know how you get on, and thanks for the issue report.
