### ISSUE TITLE
Show State Not Updating

### ISSUE THREAD

**Issue by mntechnogeek** [phuvf/oscpoint#21]
Hello!

I downloaded the latest of both Companion and OSCPoint as of today (11/24/2023). 

The Preset button for Show State: Slideshow (or Edit) doesn't seem to be updating, even after hitting "Refresh Data" button.

Media State, however, works as expected.

THX!

*FWIW, I was using the Web Buttons in the browser...not on the Stream Deck.

**Comment by phuvf** [comment]
I think this is fixed in 1.0.2.1 - let me know if you're still experiencing this issue.

**Comment by mntechnogeek** [comment]
Awesome!I'll check it out this weekend!Best,C*Sent from my Galaxy to yours 
-------- Original message --------From: Nick Roberts ***@***.***> Date: 12/13/23  2:03 AM  (GMT-06:00) To: phuvf/oscpoint ***@***.***> Cc: mntechnogeek ***@***.***>, Author ***@***.***> Subject: Re: [phuvf/oscpoint] Show State Not Updating (Issue #21) 
I think this is fixed in 1.0.2.1 - let me know if you're still experiencing this issue.
