### ISSUE TITLE
Position/remaing time refresh

### ISSUE THREAD

**Issue by nisted** [phuvf/oscpoint#24]
When shifting the position of the playhead on a paused video, the position and remaining times do not update.  While this can be got around  in companion by adding a 'refresh data' action (<250ms delay seems to be necessary) it would be ideal if this happened automatically at any playhead adjustment.

**Comment by phuvf** [comment]
Thanks for the issue report. This is a bug that I'll fix as soon as I can.

**Comment by phuvf** [comment]
v2.1
