### ISSUE TITLE
Unreliable playhead movement while video is playing.

### ISSUE THREAD

**Issue by nisted** [phuvf/oscpoint#25]
I have set a rotary button on companion to forward/rewind a video by x ms.  If the video is paused actions can be repeated very quickly, or while playing if actions are only sent once a second or so, all works fine.  
If actions are sent in quick succession (continually rolling the dial for example) the playhead jumps back to the beginning of the video.

**Comment by phuvf** [comment]
Could you send me a copy of your log files for when this happens? I'd be interested to see what get messed up in this process.

Ultimately I suspect this isn't fixable, but could put a timeout on the action so it's a bit more user friendly.

We're heading into PPT-as-a-media-server territory here - probably not a good idea!

**Comment by phuvf** [comment]
Probably not fixable due to latency issues.
