### ISSUE TITLE
Start slide show from slide x

### ISSUE THREAD

**Issue by Total-Image** [phuvf/oscpoint#26]
Would be nice to have the option to start the slideshow from a certain slide number.
/oscpoint/slideshow/start/from [integer: n]

**Comment by phuvf** [comment]
Surprisingly, there's no option in the PPT object model to do this natively - it'd have to be:

- Start slideshow
- Goto slide #

This give a flash of slide 1 each time, so isn't great - same problem applies to the 'Start from current slide' action.
When I get a bit of time I'll revisit this issue and see if there's a way to fix it.

**Comment by Total-Image** [comment]
Ah ok, then I first have to check with the OSC feedback if the slideshow is running, then use the goto action to jump to slide x and check the OSC feedback again if the current slide is slide x. When all this is set, then I can switch the videomixer input.

**Comment by phuvf** [comment]
Added to v2.x
