### ISSUE TITLE
sectionName feedback not updated on first "Go to first slide in section"

### ISSUE THREAD

**Issue by mdgnys** [phuvf/oscpoint#28]
Using Companion, I have a few buttons with feedback of "if sectionName=<section>" that also send a "Goto first slide in section" for that section.  It takes two presses of that button for the feedback to update, as it seems (per the log) feedback is not sent when changing sections using this action.  Slide number and section index both seem to update, but section name seems to lag until the next move.  

Thanks for the great tool!

**Comment by phuvf** [comment]
Fixed in v2.x
