### ISSUE TITLE
Change status feedback from "slideshow" to "Live"

### ISSUE THREAD

**Issue by PhillPower** [phuvf/oscpoint#29]
Please change the reported state of the presentation $(OSCPoint:state) values from "slideshow / edit" to "Live / Edit"

Reason: to fit the text on the buttons better.

**Comment by phuvf** [comment]
For now, I'm going to stick with 'slideshow' here, as I'm trying to keep OSCPoint as close to the PowerPoint object model as possible. Additionally, "Live" can mean lots of different things - particularly in main/backup systems e.g. a backup PPT running a slideshow would be labelled as 'Live', even though it's not actually live to air.

If you'd like to use 'Live' and 'Edit' as labels, this is possible by running a JavaScript ternary operator on the $(OSCPoint:state) variable and using this as the button text.

Further discussion welcome, of course.
