### ISSUE TITLE
Minor sync issues due to non bundled playhead information

### ISSUE THREAD

**Issue by fusionstream** [phuvf/oscpoint#31]
As the remaining time in a video and the elapsed time in a video are not reported in the same message, there is a slight difference in reported playhead position depending on which is relied upon.

Bundling these (with the "duration") in one message would alleviate this issue.

**Comment by phuvf** [comment]
Yes, this is a side-effect of the way the OSC is packaged and emitted. I've been staying away from bundles as I'm not sure how good support for them is and wanted v1 to be (a bit more) guaranteed to work. Might add support for bundles future releases - let me know if you've ever had issues with them and had to drop back to plain-ol single messages.

**Comment by fusionstream** [comment]
Not really. The individual addresses still
