### ISSUE TITLE
Incorrect total slide count when multiple files are open but not being presented

### ISSUE THREAD

**Issue by fusionstream** [phuvf/oscpoint#32]
When a deck is in focus via clicking or alt-tabbing, the total slide count is updated, even if not being presented.

However, if two decks are open, and the first is in presentation mode, escaped, and then closed with ctrl+w... resulting in the second deck now getting focus, the slide count reported for the second deck then becomes 0.

**Comment by fusionstream** [comment]
This cannot be then resolved by shifting focus out of the second deck to another Windows window. It must be defocused then focused between the second deck and yet another deck

**Comment by phuvf** [comment]
Thanks for the issue report - I'll take a look at this.

**Comment by phuvf** [comment]
v2.1
