### ISSUE TITLE
Companion buttons showing remaining time of video

### ISSUE THREAD

**Issue by addo-00** [phuvf/oscpoint#34]
On the main page with the image of a Companion layout, it shows the time remaining split across 2 buttons - minutes on one button and seconds on the other.
I can only see in the list of variables within Companion to have either seconds or to have the time formatted as mm:ss  Obviously, It's not a great hardship to have the time on one button, it does save a button after all, but for me it's easier to read! :D 

Thanks

**Comment by phuvf** [comment]
You can do this using the expressions option in Companion, and then trimming the variables to suit. Use the blue button at the end of the button text field to switch modes.

Here's an example showing the first two digits of the media position variable - this would display **mm**:

<img width="487" alt="Screenshot 2024-04-15 090927" src="https://github.com/phuvf/oscpoint/assets/3513020/3890f854-59a3-4277-8b70-6640502fbc9a">
