### ISSUE TITLE
Ability to stop presenters click out of end of slideshow

### ISSUE THREAD

**Issue by bscav** [phuvf/oscpoint#35]
Hi!

This is a request for one of my main problems with powerpoint. It's not really connected with OSC functionality which is great, but maybe it could be a part of that plugin.

The problem is presenters clicking out of the presentation, either to desktop or black slide depending on the setting. There is no option inside powerpoint to get to last slide and stay there until I manually close the presentation, which is the desired outcome.

Maybe you could somehow add a checkbox in the plugin config to not let powerpoint exit the presentation mode.
Maybe it could loop the last slide or something like that.

I and other event techs around the world would be very grateful to You for that functionality.

TIA

**Comment by phuvf** [comment]
That's a great suggestion - thanks for taking the time to send it over.

I'm not sure exactly what is possible here, as we'd need to intercept the final click and cancel it, but I'll have a play around and see.

**Comment by fusionstream** [comment]
If interception is not possible, an alternative would be to manually duplicate the last slide sans animations (which is not uncommon among some operators), then this plugin would be able to move back to the new "second last slide" on entering the "new last slide". Slide count report is reduced by 1 but there's nothing to be done with the presenter view.

An "I love life and everyone in the world" solution if interception is not possible is to automate the slide dup (sans anims) on entering slideshow mode. Just putting it out there. heehee

**Comment by phuvf** [comment]
With a bit more thought, I don't think I'm going to include this into OSCPoint. OSCPoint is really all about adding OSC control to PPT, and this would work better as a standalone add-in.

Might still have a crack at this in the future.
