### ISSUE TITLE
Is there "open" source code?

### ISSUE THREAD

**Issue by adamflorizone** [phuvf/oscpoint#36]
I see the MIT license. Is there source code? I checked all branched, tags and archives.

```OSCPoint is a PowerPoint add-in that allows Open Sound Control (OSC) control of PowerPoint on Windows```
 Is this only documentation?

**Comment by phuvf** [comment]
Unfortunately the add-in uses some code snippets and techniques we've developed as part of our OctoCue and DeckTrack add-in products, so I'm not able to open-source the code.

Thanks for asking, though.
