### ISSUE TITLE
Osc-command to set osc-feedbacks

### ISSUE THREAD

**Issue by sytem** [phuvf/oscpoint#5]
Idea for feature: 

Osc-command that can be used to activate/deactivate sending of  status messages. Maybe even to set destination ip+port.

Usecase: when having multiple ppt-computers, main+spare and maybe also other for house slides. Changing video mixer input should also change what state to monitor. All pcs sending to same ip + port, only one active at the time would do the thing.

**Comment by phuvf** [comment]
Thanks for the idea. I was considering something like this when I put together the first draft specification.

Now someone else has also suggested it I'll bump it up the roadmap.

**Comment by phuvf** [comment]
Done as of v1.0.1.1
